
name = "ICA Banken"

[currency_format]
thousands_separator = ' '
decimal_point = ','

[csv]
delimiter = ';'
date_format = '%Y-%m-%d'

[ynab_mapping]
date = 'Datum'
inflow = 'Belopp'
outflow = 'Belopp'
payee = 'Text'
