name = "Nordea"

[currency_format]
thousands_separator = ''
decimal_point = ','

[csv]
delimiter = ';'
date_format = '%Y-%m-%d'

[ynab_mapping]
date = 'Bokföringsdag'
amount = 'Belopp'
payee = 'Payee'
memo = 'Rubrik'
