[project]
name = "bank2ynab"
description = ""
version = "0.1.0"
authors = [{ name = "Adrian Nilsson" }]
requires-python = ">=3.14,<4"
license = "MIT"
dependencies = []

[dependency-groups]
dev = ["pytest>=9.0.0,<10", "hypothesis>=6.152.7,<7", "ruff>=0.15.13,<1"]

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"

[tool.ruff]
lint.ignore = ["E731"]
lint.extend-select = ["I"]
