name = "You Need a Bank"

[csv]
delimiter = ',' # defaults to ','
date_format = '%Y-%m-%d' # a valid `datetime.strptime` format string (use a TOML literal to avoid escaping)

# The full YNAB4 header is: ['Date', 'Payee', 'Category', 'Memo', 'Outflow', 'Inflow']
# Only 'Date' is strictly required to have a value, but having neither 'Outflow'
# nor 'Inflow' makes little sense.
#
# If this bank uses an 'Amount' column instead of 'Outflow' and 'Inflow', you
# can map the 'amount' key instead. You should only ever map either both
#'outflow' and 'inflow', or just 'amount'. Specifying both formats is an error.
#
# If this bank uses split columns instead of a single 'Payee' column, you are
# best of setting payee='Sender' since you probably have more rows with
# outflow than inflow. Split payee columns could be unified, but this is not
# supported.
#
# The mapped names are case insensitive.
#
[ynab_mapping]
date = 'Date' # required
outflow = 'Outflow'
inflow = 'Inflow'
#amount = 'Amount' # can replace ynab_mapping.outflow and ynab_mapping.inflow
payee = 'Payee'
memo = 'Memo'
category= 'Category'