name = "The name of your bank"

[csv]
delimiter = ','          # defaults to ','
date_format = '%Y-%m-%d' # a valid `datetime.strptime` format string (use a TOML literal to avoid escaping); see https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

[currency_format]
thousands_separator = '' # required, even if no separator is used, in which case set it to the empty string
decimal_point = '.'      # required

# The full YNAB4 header is: ['Date', 'Payee', 'Category', 'Memo', 'Outflow', 'Inflow']
# Only Date is strictly required to have a value, but having neither Outflow
# nor Inflow makes little sense.
#
# Keys 'outflow' and 'inflow' expect either a single column name or a list of
# column names. All listed columns count towards the total that is imported
# to YNAB. For example, some banks have extra columns for transaction fees.
# To find the grand total, we have to sum the transaction amount and the fees.
#
# If the bank uses an Amount column instead of Outflow and Inflow, you
# should map that column to both 'outflow' and 'inflow'.
#
# If the bank uses split columns instead of a single Payee column, you are
# best off setting payee='Sender' since you probably have more rows with
# outflow than inflow. Split payee columns could be unified, but this is not
# implemnted.
#
# The mapped names are case insensitive.
#
[ynab_mapping]
date = 'Date'         # required
outflow = 'Outflow'
inflow = 'Inflow'
payee = 'Payee'
memo = 'Memo'
category = 'Category'
